### ISSUE TITLE
Running dart.server --host 0.0.0.0 --port 7007 failed

### ISSUE THREAD

**Issue by JV-X** [juanmc2005/diart#254]
Hello, I installed the diart project on my computer. After installing the dependencies, I tried to execute the ```dart.server --host 0.0.0.0 --port 7007``` command, but the following error occurred

```
(diart) hygx@hygx:~/code$ diart.serve --host 0.0.0.0 --port 7007

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/hygx/anaconda3/envs/diart/bin/diart.serve", line 5, in <module>
    from diart.console.serve import run
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/__init__.py", line 1, in <module>
    from .blocks import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/__init__.py", line 1, in <module>
    from .aggregation import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/aggregation.py", line 5, in <module>
    from pyannote.core import Segment, SlidingWindow, SlidingWindowFeature
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/core/__init__.py", line 48, in <module>
    from .notebook import notebook
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/core/notebook.py", line 111, in <module>
    import matplotlib
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/hygx/anaconda3/envs/diart/bin/diart.serve", line 5, in <module>
    from diart.console.serve import run
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/__init__.py", line 1, in <module>
    from .blocks import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/__init__.py", line 1, in <module>
    from .aggregation import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/aggregation.py", line 5, in <module>
    from pyannote.core import Segment, SlidingWindow, SlidingWindowFeature
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/core/__init__.py", line 48, in <module>
    from .notebook import notebook
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/core/notebook.py", line 366, in <module>
    notebook = Notebook()
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/core/notebook.py", line 126, in __init__
    self.reset()
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/core/notebook.py", line 129, in reset
    from matplotlib.cm import get_cmap
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/hygx/anaconda3/envs/diart/bin/diart.serve", line 5, in <module>
    from diart.console.serve import run
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/__init__.py", line 1, in <module>
    from .blocks import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/__init__.py", line 9, in <module>
    from .embedding import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/embedding.py", line 8, in <module>
    from ..models import EmbeddingModel
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/models.py", line 13, in <module>
    from pyannote.audio import Model
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pyannote/audio/core/inference.py", line 33, in <module>
    from pytorch_lightning.utilities.memory import is_oom_error
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 42, in <module>
    from torchmetrics import Metric
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/__init__.py", line 37, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/utilities/checks.py", line 26, in <module>
    from torchmetrics.metric import Metric
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/metric.py", line 43, in <module>
    from torchmetrics.utilities.plot import _AX_TYPE, _PLOT_OUT_TYPE, plot_single_or_multi_val
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/torchmetrics/utilities/plot.py", line 26, in <module>
    import matplotlib
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/hygx/anaconda3/envs/diart/bin/diart.serve", line 5, in <module>
    from diart.console.serve import run
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/__init__.py", line 1, in <module>
    from .blocks import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/__init__.py", line 16, in <module>
    from .diarization import SpeakerDiarization, SpeakerDiarizationConfig
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/diarization.py", line 12, in <module>
    from . import base
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/base.py", line 8, in <module>
    from .. import utils
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/utils.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/home/hygx/anaconda3/envs/diart/bin/diart.serve", line 5, in <module>
    from diart.console.serve import run
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/__init__.py", line 1, in <module>
    from .blocks import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/__init__.py", line 16, in <module>
    from .diarization import SpeakerDiarization, SpeakerDiarizationConfig
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/diarization.py", line 12, in <module>
    from . import base
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/blocks/base.py", line 8, in <module>
    from .. import utils
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/diart/utils.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```

After searching I tried downgrading numpy to 1.8.0, but got another error：
```
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```
I'm not sure what to do, so I'd like to hear your advice.

and one more question,I want to use ```diart``` with websocket, but I only see some backend code snippets in the document (as shown below), but no frontend javascript.

```
from diart import SpeakerDiarization
from diart.sources import WebSocketAudioSource
from diart.inference import StreamingInference

pipeline = SpeakerDiarization()
source = WebSocketAudioSource(pipeline.config.sample_rate, "localhost", 7007)
inference = StreamingInference(pipeline, source)
inference.attach_hooks(lambda ann_wav: source.send(ann_wav[0].to_rttm()))
prediction = inference()
```
Where should I get the front-end javascript code?

thanks for your reply.

**Comment by JV-X** [comment]
I tested the same operation on a Windows 11 desktop and a Mac laptop and got the same error.
My operation:

```
git clone https://github.com/juanmc2005/diart.git
```
```
conda env create -f diart/environment.yml
```
```
conda activate diart
```
```
pip install diart
```
```
diart.serve --host 0.0.0.0 --port 7007
```

**Comment by ywangwxd** [comment]
Come on, the error message has remind you.

> A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2

Have you tried donwgrading numpy to, say, 1.19?

**Comment by JV-X** [comment]
> Come on, the error message has remind you.
> 
> > A module that was compiled using NumPy 1.x cannot be run in
> > NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
> > versions of NumPy, modules must be compiled with NumPy 2.0.
> > Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> Have you tried donwgrading numpy to, say, 1.19?

I have tried to install an earlier version of numpy before, but I keep getting the following error. I have tried reinstalling or upgrading or downgrading setuptool, wheel, distutils, etc. according to answers on the Internet, but none of them can solve this problem.

```
(diart) hygx@hygx:~/code/diart/numpy-1.19.0$ pip install numpy==1.19
Collecting numpy==1.19
  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Traceback (most recent call last):
        File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-wzabb6e8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-wzabb6e8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-wzabb6e8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 465, in setup_package
        File "/tmp/pip-install-heeb6k69/numpy_387d451b6ab046f8bab3d6a28cec7735/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/tmp/pip-install-heeb6k69/numpy_387d451b6ab046f8bab3d6a28cec7735/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/tmp/pip-install-heeb6k69/numpy_387d451b6ab046f8bab3d6a28cec7735/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ywangwxd** [comment]
> > Come on, the error message has remind you.
> > > A module that was compiled using NumPy 1.x cannot be run in
> > > NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
> > > versions of NumPy, modules must be compiled with NumPy 2.0.
> > > Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> > 
> > 
> > Have you tried donwgrading numpy to, say, 1.19?
> 
> I have tried to install an earlier version of numpy before, but I keep getting the following error. I have tried reinstalling or upgrading or downgrading setuptool, wheel, distutils, etc. according to answers on the Internet, but none of them can solve this problem.
> 
> ```
> (diart) hygx@hygx:~/code/diart/numpy-1.19.0$ pip install numpy==1.19
> Collecting numpy==1.19
>   Using cached numpy-1.19.0.zip (7.3 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [24 lines of output]
>       Running from numpy source directory.
>       <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
>       Traceback (most recent call last):
>         File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/home/hygx/anaconda3/envs/diart/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
>           return hook(metadata_directory, config_settings)
>         File "/tmp/pip-build-env-wzabb6e8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
>           self.run_setup()
>         File "/tmp/pip-build-env-wzabb6e8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/tmp/pip-build-env-wzabb6e8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
>           exec(code, locals())
>         File "<string>", line 489, in <module>
>         File "<string>", line 465, in setup_package
>         File "/tmp/pip-install-heeb6k69/numpy_387d451b6ab046f8bab3d6a28cec7735/numpy/distutils/core.py", line 24, in <module>
>           from numpy.distutils.command import config, config_compiler, \
>         File "/tmp/pip-install-heeb6k69/numpy_387d451b6ab046f8bab3d6a28cec7735/numpy/distutils/command/config.py", line 19, in <module>
>           from numpy.distutils.mingw32ccompiler import generate_manifest
>         File "/tmp/pip-install-heeb6k69/numpy_387d451b6ab046f8bab3d6a28cec7735/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
>           from distutils.msvccompiler import get_build_version as get_build_msvc_version
>       ModuleNotFoundError: No module named 'distutils.msvccompiler'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```

Can you try other version too? Your problem is about the environment, so solve it first.  And this error message told you something:

> ModuleNotFoundError: No module named 'distutils.msvccompiler'

Please read the error message carefully, because most of the time it would give you hint what to do.

**Comment by JV-X** [comment]
thanks for your reply

**Comment by JV-X** [comment]
Finally I solved the environment problem. First, the `CUDA` environment needs to be `11.6`, and then the `numpy` version needs to be `1.24.4` (sometimes pip will install the wrong path directly, so you need to use `python -m pip install` instead of `pip install` directly)
